In [1]:

import bs4
import os
import csv
import re

In [2]:
from save_data import *
import pandas as pd

In [ ]:
# 禁用 Pandas 的显示截断
# import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [3]:

# 读取清洗后的HTML文件
# input_path = r"input\2025年5月份70个大中城市商品住宅销售价格变动情况2.html"
# input_path = r"input\201801.html"
input_path = r"stats_search_selenium_local_debug.html"

with open(input_path, 'r', encoding='utf-8') as f:
    html = f.read()

In [4]:
soup = bs4.BeautifulSoup(html, 'html.parser')

In [16]:
pattern = r'(\d{4})年(\d{1,2})月份70个大中城市商品住宅销售价格变动情况'


def match_title(s):
    match = re.fullmatch(pattern, s)
    year = ""
    month = ""
    if match:
        year = match.group(1)
        month = match.group(2).zfill(2)
        # print(f"匹配成功: '{s}' → 年份: {year}, 月份: {month}")
        return year+month
    else:
        # print(f"不匹配: '{s}'")
        pass
        return None

In [17]:
href = soup.find_all("a")

In [18]:
for i in href:
    res = match_title(i.text)
    if res:
        print(res)
    # print(i.text)

201808
201812
201811
201810
201809
201803
201804
201807
201806
201805
201801
201802

In [27]:
caption = soup.find('p')
time_str = ''
if caption:
    cap_text = caption.get_text()
    m = re.search(r'(\d{4})年(\d{1,2})月', cap_text)
    if m:
        time_str = f"{m.group(1)}{m.group(2).zfill(2)}"
    else:
        time_str = cap_text.strip()
else:
    time_str = '未知时间'

In [ ]:
# time_int = int(time_str)
time_str # TODO 2018 diff

'2018/02/24 09:30'

In [29]:
all_data={}
each_dict={}

In [30]:
# 提取所有表格
tables = soup.find_all('table')
print(f"共找到 {len(tables)} 个表格")

共找到 10 个表格

In [31]:
def replace_empty(s:str):
    s = s.replace('\u3000', '').replace('\xa0', '').replace(' ', '').replace('\t', '').replace('\n', '').replace('\r', '')
    return s

In [32]:
if tables:
    table = tables[0]

In [37]:
str_ = "月70个大中城市新建商品住宅销售价格指数"
for i, t in enumerate(tables):
    tmp = t.find_previous("div").find_previous("div").text
    if str_ in tmp:
        print(i)

0
5

In [33]:
str_ = "月70个大中城市新建商品住宅销售价格指数"
for t in tables:
    tmp = t.find_previous("div").find_previous("div").text
    if str_ in tmp:
        print(str_)

月70个大中城市新建商品住宅销售价格指数
月70个大中城市新建商品住宅销售价格指数

In [34]:
tables[0].find_previous("div").find_previous("div").text

'表1:\u3000 15个热点城市新建商品住宅销售价格变动对比表    城市   同比（上年同月=100）   环比（上月=100）     2018年1月   2017年12月   2018年1月   2017年12月     北京   98.8    99.8   100.2    100.0     天津   99.9   100.1   100.5   100.2     上海   99.8    100.2   99.6    100.3     南京   98.0    98.6   99.7    100.1     无锡   97.3    98.9   99.7    100.2     杭州   99.0    99.4   100.0    100.0     合肥   99.7    99.8   99.9   100.0     福州   97.7    98.3   100.0    99.8     厦门   102.3    102.2   99.7   99.8     济南   100.9   100.9   100.5    100.3     郑州   99.0    99.3   99.7   100.3     武汉   100.7   100.6   100.4    100.3     广州   103.7    105.5   99.6   99.7     深圳   96.6   97.0   100.0    99.8     成都   98.7    99.4   100.2    100.5   \xa0表2：2018年1月70个大中城市新建商品住宅销售价格指数    城市   环比   同比   定基   城市   环比   同比   定基     上月=100   上年同月=100   2015年 =100   上月=100   上年同月=100   2015年 =100     北\u3000\u3000京   100.2    98.8    133.6    唐\u3000\u3000山   100.7    106.9    109.4      天\u3000\u3000津   100.5    99.9    128.0    秦 皇 岛   100.8    105.8    112.4      石 家 庄   100.1    102.6    123.6    包\u3000\u3000头   100.8    103.8    102.7      太\u3000\u3000原   100.5    107.8    112.3    丹\u3000\u3000东   100.1    104.2    102.0      呼和浩特   100.1    106.8    107.2    锦\u3000\u3000州   100.4    100.9    96.9      沈\u3000\u3000阳   100.9    111.4    114.9    吉\u3000\u3000林   100.5    108.1    109.6      大\u3000\u3000连   101.6    110.4    112.4    牡 丹 江   100.3    106.9    105.0      长\u3000\u3000春   100.7    109.5    113.4    无\u3000\u3000锡   99.7    97.3    131.0      哈 尔 滨   100.1    111.5    114.3    扬\u3000\u3000州   100.9    109.1    121.0      上\u3000\u3000海   99.6    99.8    145.1    徐\u3000\u3000州   100.6    108.3    119.3      南\u3000\u3000京   99.7    98.0    145.3    温\u3000\u3000州   100.4    107.2    114.0      杭\u3000\u3000州   100.0    99.0    132.6    金\u3000\u3000华   100.2    109.3    118.7      宁\u3000\u3000波   100.7    106.2    121.7    蚌\u3000\u3000埠   99.9    108.4    117.2      合\u3000\u3000肥   99.9    99.7    148.3    安\u3000\u3000庆   100.5    105.7    113.5      福\u3000\u3000州   100.0    97.7    127.0    泉\u3000\u3000州   99.7    100.1    110.1      厦\u3000\u3000门   99.7    102.3    151.6    九\u3000\u3000江   100.5    108.3    121.2      南\u3000\u3000昌   99.9    106.0    123.6    赣\u3000\u3000州   100.2    101.1    115.1      济\u3000\u3000南   100.5    100.9    121.5    烟\u3000\u3000台   101.0    109.5    115.5      青\u3000\u3000岛   100.1    103.6    117.3    济\u3000\u3000宁   100.2    109.8    110.3      郑\u3000\u3000州   99.7    99.0    129.4    洛\u3000\u3000阳   100.5    108.9    113.6      武\u3000\u3000汉   100.4    100.7    129.9    平 顶 山   100.6    107.0    111.3      长\u3000\u3000沙   100.4    105.4    125.9    宜\u3000\u3000昌   100.9    108.2    114.2      广\u3000\u3000州   99.6    103.7    136.4    襄\u3000\u3000阳   101.2    106.7    108.4      深\u3000\u3000圳   100.0    96.6    144.3    岳\u3000\u3000阳   100.0    107.9    112.8      南\u3000\u3000宁   100.1    108.4    123.1    常\u3000\u3000德   100.3    110.2    112.5      海\u3000\u3000口   100.4    101.7    108.7    惠\u3000\u3000州   100.0    103.7    130.5      重\u3000\u3000庆   100.3    108.3    118.0    湛\u3000\u3000江   100.1    108.3    116.2      成\u3000\u3000都   100.2    98.7    105.5    韶\u3000\u3000关   99.5    104.3    112.1      贵\u3000\u3000阳   101.0    111.2    117.1    桂\u3000\u3000林   99.8    107.2    110.1      昆\u3000\u3000明   101.4    110.6    114.5    北\u3000\u3000海   99.7    110.5    115.2      西\u3000\u3000安   100.6    111.1    121.1    三\u3000\u3000亚   100.9    103.3    110.0      兰\u3000\u3000州   100.4    105.3    109.2    泸\u3000\u3000州   100.8    106.6    110.3      西\u3000\u3000宁   100.2    105.7    107.0    南\u3000\u3000充   100.3    109.9    110.5      银\u3000\u3000川   100.4    104.1    105.0    遵\u3000\u3000义   101.1    107.9    109.2      乌鲁木齐   100.4    107.5    105.2    大\u3000\u3000理   100.7    106.4    108.9    \xa0表3：2018年1月70个大中城市二手住宅销售价格指数    城市   环比   同比   定基   城市   环比   同比   定基     上月=100   上年同月=100   2015年 =100   上月=100   上年同月=100   2015年 =100     北\u3000\u3000京   99.4    96.9    146.8    唐\u3000\u3000山   100.0    103.3    105.3      天\u3000\u3000津   100.6    98.2    125.1    秦 皇 岛   100.0    105.4    108.4      石 家 庄   99.6    99.8    118.3    包\u3000\u3000头   99.9    102.6    100.3      太\u3000\u3000原   100.9    108.3    114.9    丹\u3000\u3000东   100.3    102.7    100.7      呼和浩特   100.3    102.8    101.8    锦\u3000\u3000州   100.0    100.2    93.6      沈\u3000\u3000阳   100.1    107.3    109.0    吉\u3000\u3000林   100.2    103.8    105.5      大\u3000\u3000连   100.7    105.9    107.2    牡 丹 江   99.8    102.9    103.5      长\u3000\u3000春   100.5    105.5    106.5    无\u3000\u3000锡   99.9    108.5    129.1      哈 尔 滨   100.2    106.6    108.6    扬\u3000\u3000州   100.2    105.5    112.3      上\u3000\u3000海   100.1    100.8    141.5    徐\u3000\u3000州   100.3    105.3    110.9      南\u3000\u3000京   99.6    97.6    135.2    温\u3000\u3000州   99.9    106.4    111.5      杭\u3000\u3000州   100.2    106.9    134.3    金\u3000\u3000华   100.3    107.5    113.5      宁\u3000\u3000波   100.4    107.2    118.3    蚌\u3000\u3000埠   100.0    107.1    112.3      合\u3000\u3000肥   100.0    99.3    151.4    安\u3000\u3000庆   99.9    105.9    113.2      福\u3000\u3000州   99.9    104.9    125.6    泉\u3000\u3000州   100.0    105.9    112.4      厦\u3000\u3000门   99.2    102.2    140.7    九\u3000\u3000江   100.3    104.4    114.6      南\u3000\u3000昌   99.9    103.1    118.2    赣\u3000\u3000州   100.4    102.7    113.7      济\u3000\u3000南   99.6    102.3    119.4    烟\u3000\u3000台   100.3    106.5    109.2      青\u3000\u3000岛   100.1    110.6    122.7    济\u3000\u3000宁   100.2    106.6    107.9      郑\u3000\u3000州   99.5    99.7    130.3    洛\u3000\u3000阳   100.2    104.2    106.6      武\u3000\u3000汉   100.3    108.8    136.8    平 顶 山   100.6    105.6    106.0      长\u3000\u3000沙   100.2    110.6    126.2    宜\u3000\u3000昌   101.0    106.6    111.4      广\u3000\u3000州   99.9    107.6    145.9    襄\u3000\u3000阳   100.7    105.7    106.4      深\u3000\u3000圳   100.9    102.6    145.3    岳\u3000\u3000阳   100.2    104.6    107.2      南\u3000\u3000宁   100.2    107.0    115.7    常\u3000\u3000德   100.0    104.2    106.7      海\u3000\u3000口   100.5    100.6    103.6    惠\u3000\u3000州   100.3    106.0    122.8      重\u3000\u3000庆   100.1    108.0    115.6    湛\u3000\u3000江   100.3    107.4    109.4      成\u3000\u3000都   99.7    103.5    110.2    韶\u3000\u3000关   99.7    105.1    107.0      贵\u3000\u3000阳   100.5    104.9    107.9    桂\u3000\u3000林   100.1    103.1    100.2      昆\u3000\u3000明   100.7    106.4    108.9    北\u3000\u3000海   99.9    108.0    112.1      西\u3000\u3000安   100.0    108.9    105.1    三\u3000\u3000亚   100.1    101.7    105.5      兰\u3000\u3000州   100.7    103.5    104.7    泸\u3000\u3000州   100.3    104.4    109.0      西\u3000\u3000宁   100.3    102.5    101.7    南\u3000\u3000充   100.5    107.0    110.3      银\u3000\u3000川   100.2    101.2    100.5    遵\u3000\u3000义   100.7    105.3    106.5      乌鲁木齐   101.1    109.5    107.8    大\u3000\u3000理   100.7    102.9    101.6    \xa0表4：2018年1月70个大中城市新建商品住宅销售价格分类指数    城市   90m2及以下   90-144m2   144m2以上     环比   同比   定基   环比   同比   定基   环比   同比   定基     上月 =100   上年同月            =100   2015年 =100   上月 =100   上年同月 =100   2015年 =100   上月 =100   上年同月 =100   2015年 =100     北\u3000\u3000京   100.2    99.9    121.4    99.9    99.0    137.3    100.4    98.0    139.9      天\u3000\u3000津   100.5    100.1    133.7    100.5    98.9    126.8    100.4    101.5    126.1      石 家 庄   100.7    102.7    122.2    100.3    102.9    124.6    99.3    101.8    121.7      太\u3000\u3000原   100.0    107.9    114.6    100.7    108.7    113.8    100.5    106.4    109.5      呼和浩特   100.3    106.4    103.7    99.9    105.9    107.4    100.3    108.9    108.6      沈\u3000\u3000阳   101.3    112.3    118.1    100.8    112.0    114.8    100.1    109.1    109.4      大\u3000\u3000连   101.3    110.1    111.7    102.0    111.8    116.4    101.5    108.0    106.4      长\u3000\u3000春   101.2    111.9    118.0    100.3    109.4    111.8    100.5    106.6    110.3      哈 尔 滨   99.9    112.9    114.8    99.9    112.0    115.5    100.6    109.2    111.5      上\u3000\u3000海   99.9    100.0    147.4    99.1    99.7    146.0    99.9    99.8    143.4      南\u3000\u3000京   99.8    99.3    150.7    99.7    97.9    144.9    99.7    97.1    141.6      杭\u3000\u3000州   100.0    99.2    137.3    99.8    98.4    131.5    100.0    99.4    128.2      宁\u3000\u3000波   101.1    107.7    126.3    100.4    105.4    121.2    100.9    106.8    120.5      合\u3000\u3000肥   99.8    98.5    146.5    99.9    100.0    148.8    100.2    100.4    148.8      福\u3000\u3000州   99.4    95.0    124.6    99.9    96.7    126.1    100.3    100.7    129.4      厦\u3000\u3000门   99.9    102.1    151.4    99.6    102.4    152.2    99.8    102.3    150.7      南\u3000\u3000昌   100.4    108.3    127.7    99.9    106.2    123.8    99.7    103.8    120.4      济\u3000\u3000南   100.3    99.4    119.0    100.2    101.0    122.5    101.4    101.3    119.7      青\u3000\u3000岛   100.1    103.0    116.9    100.0    103.6    118.6    100.1    104.8    115.4      郑\u3000\u3000州   99.9    99.7    131.9    99.4    98.8    128.6    100.0    97.7    124.4      武\u3000\u3000汉   100.3    100.4    129.8    100.3    101.0    131.0    100.5    99.9    126.0      长\u3000\u3000沙   100.9    105.3    123.4    100.1    105.3    126.2    100.4    105.4    127.1      广\u3000\u3000州   99.7    105.0    138.7    99.6    103.4    136.3    99.6    103.6    135.4      深\u3000\u3000圳   99.7    96.9    143.7    99.6    96.3    143.6    101.0    96.2    146.1      南\u3000\u3000宁   100.2    109.5    125.1    99.8    106.6    121.7    100.3    110.5    122.4      海\u3000\u3000口   100.2    97.6    106.4    100.4    103.0    110.4    100.9    102.5    106.6      重\u3000\u3000庆   100.1    110.4    120.2    100.3    106.6    116.6    100.5    108.0    117.0      成\u3000\u3000都   99.8    99.7    105.1    100.5    97.1    105.4    100.5    99.5    106.6      贵\u3000\u3000阳   100.6    112.7    118.6    101.3    111.0    117.6    100.6    109.5    113.3      昆\u3000\u3000明   101.3    109.8    114.8    101.5    110.4    114.5    101.5    111.6    114.0      西\u3000\u3000安   99.7    110.2    121.2    100.8    112.1    121.5    100.9    110.3    120.2      兰\u3000\u3000州   100.9    105.6    109.7    100.1    105.7    109.2    100.2    104.0    108.1      西\u3000\u3000宁   100.2    107.0    109.0    100.2    106.0    107.0    100.0    104.4    105.9      银\u3000\u3000川   100.4    104.4    105.8    100.1    104.0    104.8    101.1    104.5    105.1      乌鲁木齐   100.1    107.7    104.7    100.6    108.1    107.1    100.0    105.6    100.2      唐\u3000\u3000山   100.2    105.9    108.8    101.0    107.0    109.9    100.5    107.8    109.1      秦 皇 岛   100.6    107.0    113.1    101.0    105.9    113.5    100.3    104.1    107.5      包\u3000\u3000头   100.9    109.2    107.5    101.0    103.0    102.7    100.5    102.7    99.8      丹\u3000\u3000东   100.0    104.7    103.5    100.1    104.2    102.3    100.0    103.4    97.9      锦\u3000\u3000州   100.4    101.9    94.8    100.5    100.5    97.9    100.0    99.9    96.1      吉\u3000\u3000林   100.7    107.6    108.9    100.2    108.1    109.8    100.7    109.4    110.5      牡 丹 江   100.4    107.2    103.8    100.2    107.4    106.5    100.3    102.5    99.9      无\u3000\u3000锡   99.6    98.5    135.5    99.7    98.0    134.1    99.6    94.9    121.8      扬\u3000\u3000州   101.1    108.8    121.5    100.8    108.6    121.1    101.0    111.2    120.4      徐\u3000\u3000州   100.2    109.1    120.3    100.6    108.3    119.4    100.7    107.3    118.1      温\u3000\u3000州   100.7    105.6    111.1    100.5    106.8    115.3    100.0    108.9    114.4      金\u3000\u3000华   100.3    109.9    120.8    100.5    109.5    120.0    99.9    108.4    114.8      蚌\u3000\u3000埠   100.9    109.0    117.8    99.5    108.5    117.3    99.7    104.0    111.6      安\u3000\u3000庆   100.2    105.8    114.4    100.6    105.7    113.5    100.2    105.0    112.0      泉\u3000\u3000州   99.4    101.2    110.8    99.7    100.2    110.1    99.9    99.3    109.6      九\u3000\u3000江   100.7    110.4    123.6    100.6    108.1    121.1    100.1    107.5    119.8      赣\u3000\u3000州   100.4    102.3    117.0    100.1    100.5    114.1    100.7    102.2    117.5      烟\u3000\u3000台   100.8    108.4    112.7    101.1    111.0    118.9    100.7    106.2    110.2      济\u3000\u3000宁   100.4    111.2    111.9    100.3    110.5    111.3    99.8    107.8    107.6      洛\u3000\u3000阳   101.2    112.1    121.6    100.3    108.3    112.4    100.8    108.2    111.0      平 顶 山   100.0    105.9    109.9    100.8    108.1    112.3    100.6    104.8    109.4      宜\u3000\u3000昌   101.4    107.1    112.6    100.8    108.8    114.8    101.1    106.0    112.8      襄\u3000\u3000阳   101.7    110.8    113.7    101.1    105.8    107.6    101.0    106.1    105.5      岳\u3000\u3000阳   100.2    106.2    111.3    100.1    111.0    114.6    99.9    102.5    110.0      常\u3000\u3000德   100.5    112.3    115.1    100.2    109.2    111.7    100.3    109.0    110.2      惠\u3000\u3000州   99.8    106.2    131.7    99.8    103.9    131.5    100.6    101.6    127.8      湛\u3000\u3000江   100.0    107.5    116.6    100.0    108.5    116.5    100.4    109.1    114.0      韶\u3000\u3000关   99.6    101.5    110.1    99.7    104.8    112.0    99.2    104.4    112.8      桂\u3000\u3000林   100.5    108.2    109.6    99.7    106.7    109.2    99.7    107.6    113.1      北\u3000\u3000海   99.8    109.7    114.9    99.7    112.0    115.8    99.9    109.5    114.8      三\u3000\u3000亚   100.9    104.9    112.4    100.7    102.6    109.1    101.1    101.8    107.3      泸\u3000\u3000州   101.0    104.8    109.8    100.7    107.1    110.4    101.0    109.1    111.4      南\u3000\u3000充   100.3    110.2    111.1    100.3    109.6    110.3    101.2    112.2    110.1      遵\u3000\u3000义   101.2    107.4    110.8    101.1    108.6    109.1    101.2    104.7    107.5      大\u3000\u3000理   101.2    110.5    113.0    100.2    104.2    107.3    101.0    106.7    108.5    \xa0表5：2018年1月70个大中城市二手住宅销售价格分类指数    城市   90m2及以下   90-144m2   144m2以上     环比   同比   定基   环比   同比   定基   环比   同比   定基     上月 =100   上年同月            =100   2015年 =100   上月 =100   上年同月 =100   2015年 =100   上月 =100   上年同月 =100   2015年 =100     北\u3000\u3000京   99.4    96.4    146.8    99.4    97.1    145.9    99.3    98.0    148.8      天\u3000\u3000津   100.6    98.4    128.3    100.4    98.7    125.2    101.0    96.1    115.1      石 家 庄   99.8    100.3    121.0    99.5    99.4    117.3    99.8    99.4    113.4      太\u3000\u3000原   100.7    107.7    115.0    101.0    109.8    116.6    101.1    107.1    111.8      呼和浩特   100.4    102.9    101.8    100.3    102.6    101.9    100.3    102.9    101.2      沈\u3000\u3000阳   100.1    107.2    108.8    100.0    107.4    110.1    100.0    108.0    107.4      大\u3000\u3000连   100.8    105.7    107.1    100.7    105.9    107.6    100.5    107.6    106.9      长\u3000\u3000春   100.6    105.3    107.4    100.3    105.5    105.5    100.4    106.5    105.5      哈 尔 滨   100.2    106.7    108.9    100.2    106.7    108.5    100.3    106.0    108.0      上\u3000\u3000海   100.3    99.7    142.1    100.0    101.6    140.8    99.7    102.1    141.4      南\u3000\u3000京   99.5    96.4    130.4    99.7    98.9    137.8    99.6    97.2    139.3      杭\u3000\u3000州   100.2    107.2    135.5    100.1    107.7    135.1    100.0    105.2    130.8      宁\u3000\u3000波   100.3    107.8    118.3    100.4    107.0    119.0    100.6    106.8    116.8      合\u3000\u3000肥   99.9    99.3    152.6    100.1    99.3    149.9    100.1    99.7    153.4      福\u3000\u3000州   99.9    105.2    125.3    99.8    104.7    124.7    100.0    104.9    127.3      厦\u3000\u3000门   99.1    103.0    144.5    99.2    102.1    139.7    99.4    101.5    137.7      南\u3000\u3000昌   100.2    104.7    121.1    99.5    102.3    116.5    100.3    99.5    113.3      济\u3000\u3000南   99.6    102.8    120.6    99.6    101.7    118.8    100.0    102.6    117.3      青\u3000\u3000岛   100.1    110.0    122.0    100.2    109.6    122.1    100.1    114.6    125.4      郑\u3000\u3000州   99.6    99.8    130.8    99.5    99.2    130.8    99.6    100.7    128.4      武\u3000\u3000汉   100.3    109.4    139.0    100.3    108.6    137.1    100.6    108.2    131.8      长\u3000\u3000沙   99.9    110.8    125.6    100.2    110.6    125.2    100.4    110.5    128.2      广\u3000\u3000州   99.9    109.2    148.3    100.1    106.3    143.9    99.7    105.4    142.7      深\u3000\u3000圳   101.0    103.7    149.4    100.6    100.9    140.7    101.2    103.0    143.6      南\u3000\u3000宁   100.1    105.2    113.2    100.1    107.1    114.5    100.6    110.7    123.2      海\u3000\u3000口   100.3    100.3    103.1    100.5    101.0    104.4    101.1    100.8    103.5      重\u3000\u3000庆   100.1    107.9    115.6    100.1    108.9    117.8    100.2    105.8    110.1      成\u3000\u3000都   99.6    103.7    111.8    99.5    102.9    108.6    100.5    104.4    109.8      贵\u3000\u3000阳   100.2    105.0    107.6    100.4    104.5    107.3    101.1    105.7    109.7      昆\u3000\u3000明   100.8    105.2    108.2    100.7    106.3    108.5    100.4    108.6    110.5      西\u3000\u3000安   100.0    110.5    106.7    100.0    108.7    105.6    100.1    106.9    101.5      兰\u3000\u3000州   100.6    103.8    106.1    100.7    103.3    104.1    100.8    103.3    103.3      西\u3000\u3000宁   100.2    102.0    101.4    100.3    102.7    101.9    100.4    102.2    101.5      银\u3000\u3000川   100.2    101.2    100.8    100.2    101.0    100.3    100.4    101.6    99.8      乌鲁木齐   101.1    111.5    108.2    101.2    108.8    108.2    101.0    104.0    104.4      唐\u3000\u3000山   100.1    103.5    105.9    100.1    103.4    105.0    99.7    101.6    103.3      秦 皇 岛   100.1    106.4    110.3    99.8    105.4    107.9    100.1    101.6    104.5      包\u3000\u3000头   99.8    101.2    98.9    100.0    104.5    102.4    100.0    100.4    97.1      丹\u3000\u3000东   100.3    102.9    100.0    100.3    102.5    102.7    100.2    102.7    97.7      锦\u3000\u3000州   100.1    100.2    93.9    100.0    100.0    93.1    100.0    101.0    94.0      吉\u3000\u3000林   100.2    103.8    105.7    100.1    103.9    105.9    100.2    103.5    102.9      牡 丹 江   99.7    102.5    104.6    100.3    105.1    101.8    99.7    98.4    92.5      无\u3000\u3000锡   100.0    108.5    130.0    99.7    108.2    128.3    100.5    109.3    129.1      扬\u3000\u3000州   100.2    106.0    112.9    100.2    105.0    111.8    100.0    105.5    111.0      徐\u3000\u3000州   100.5    105.5    111.6    100.1    104.9    110.1    100.5    106.0    112.0      温\u3000\u3000州   99.8    107.1    113.7    99.9    106.6    112.0    99.9    105.5    108.8      金\u3000\u3000华   100.2    108.2    115.5    100.3    107.5    112.5    100.4    106.6    111.8      蚌\u3000\u3000埠   100.0    107.1    112.6    100.0    107.0    112.2    100.1    107.4    111.7      安\u3000\u3000庆   99.9    105.6    113.0    99.9    106.4    113.8    100.1    105.3    111.9      泉\u3000\u3000州   100.3    105.9    112.2    99.9    106.8    112.8    100.0    104.7    112.3      九\u3000\u3000江   100.3    104.1    117.3    100.3    104.6    112.8    100.0    104.4    110.6      赣\u3000\u3000州   100.2    102.7    113.1    100.5    102.7    114.8    100.5    102.6    112.3      烟\u3000\u3000台   100.4    107.7    111.1    100.3    105.6    107.9    100.2    104.3    104.7      济\u3000\u3000宁   100.2    105.8    107.0    100.3    108.1    110.1    100.0    103.1    101.7      洛\u3000\u3000阳   100.2    104.3    107.8    100.2    104.1    106.4    100.1    104.2    105.4      平 顶 山   100.7    103.7    102.0    100.9    108.2    107.8    100.1    104.8    109.7      宜\u3000\u3000昌   100.8    106.6    112.6    101.0    106.7    111.3    100.9    106.0    108.6      襄\u3000\

In [36]:
tables[2].find_previous("div").find_previous("div").text

'    城市   环比   同比   定基   城市   环比   同比   定基     上月=100   上年同月=100   2015年 =100   上月=100   上年同月=100   2015年 =100     北\u3000\u3000京   100.2    98.8    133.6    唐\u3000\u3000山   100.7    106.9    109.4      天\u3000\u3000津   100.5    99.9    128.0    秦 皇 岛   100.8    105.8    112.4      石 家 庄   100.1    102.6    123.6    包\u3000\u3000头   100.8    103.8    102.7      太\u3000\u3000原   100.5    107.8    112.3    丹\u3000\u3000东   100.1    104.2    102.0      呼和浩特   100.1    106.8    107.2    锦\u3000\u3000州   100.4    100.9    96.9      沈\u3000\u3000阳   100.9    111.4    114.9    吉\u3000\u3000林   100.5    108.1    109.6      大\u3000\u3000连   101.6    110.4    112.4    牡 丹 江   100.3    106.9    105.0      长\u3000\u3000春   100.7    109.5    113.4    无\u3000\u3000锡   99.7    97.3    131.0      哈 尔 滨   100.1    111.5    114.3    扬\u3000\u3000州   100.9    109.1    121.0      上\u3000\u3000海   99.6    99.8    145.1    徐\u3000\u3000州   100.6    108.3    119.3      南\u3000\u3000京   99.7    98.0    145.3    温\u3000\u3000州   100.4    107.2    114.0      杭\u3000\u3000州   100.0    99.0    132.6    金\u3000\u3000华   100.2    109.3    118.7      宁\u3000\u3000波   100.7    106.2    121.7    蚌\u3000\u3000埠   99.9    108.4    117.2      合\u3000\u3000肥   99.9    99.7    148.3    安\u3000\u3000庆   100.5    105.7    113.5      福\u3000\u3000州   100.0    97.7    127.0    泉\u3000\u3000州   99.7    100.1    110.1      厦\u3000\u3000门   99.7    102.3    151.6    九\u3000\u3000江   100.5    108.3    121.2      南\u3000\u3000昌   99.9    106.0    123.6    赣\u3000\u3000州   100.2    101.1    115.1      济\u3000\u3000南   100.5    100.9    121.5    烟\u3000\u3000台   101.0    109.5    115.5      青\u3000\u3000岛   100.1    103.6    117.3    济\u3000\u3000宁   100.2    109.8    110.3      郑\u3000\u3000州   99.7    99.0    129.4    洛\u3000\u3000阳   100.5    108.9    113.6      武\u3000\u3000汉   100.4    100.7    129.9    平 顶 山   100.6    107.0    111.3      长\u3000\u3000沙   100.4    105.4    125.9    宜\u3000\u3000昌   100.9    108.2    114.2      广\u3000\u3000州   99.6    103.7    136.4    襄\u3000\u3000阳   101.2    106.7    108.4      深\u3000\u3000圳   100.0    96.6    144.3    岳\u3000\u3000阳   100.0    107.9    112.8      南\u3000\u3000宁   100.1    108.4    123.1    常\u3000\u3000德   100.3    110.2    112.5      海\u3000\u3000口   100.4    101.7    108.7    惠\u3000\u3000州   100.0    103.7    130.5      重\u3000\u3000庆   100.3    108.3    118.0    湛\u3000\u3000江   100.1    108.3    116.2      成\u3000\u3000都   100.2    98.7    105.5    韶\u3000\u3000关   99.5    104.3    112.1      贵\u3000\u3000阳   101.0    111.2    117.1    桂\u3000\u3000林   99.8    107.2    110.1      昆\u3000\u3000明   101.4    110.6    114.5    北\u3000\u3000海   99.7    110.5    115.2      西\u3000\u3000安   100.6    111.1    121.1    三\u3000\u3000亚   100.9    103.3    110.0      兰\u3000\u3000州   100.4    105.3    109.2    泸\u3000\u3000州   100.8    106.6    110.3      西\u3000\u3000宁   100.2    105.7    107.0    南\u3000\u3000充   100.3    109.9    110.5      银\u3000\u3000川   100.4    104.1    105.0    遵\u3000\u3000义   101.1    107.9    109.2      乌鲁木齐   100.4    107.5    105.2    大\u3000\u3000理   100.7    106.4    108.9    '

In [11]:
# table.find_previous("div").get_text(strip=True)
table.find_previous("div").find_previous("div").text

'表1：2025年5月70个大中城市新建商品住宅销售价格指数\u2002\n\n\n\n城市\n\n环比\n\n同比\n\n1-5月平均\n\n城市\n\n环比\n\n同比\n\n1-5月平均\n\n\n上月=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n上月=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n\n北\u3000\u3000京\n\n99.6\n\n95.7\n\n94.7\n\n唐\u3000\u3000山\n\n99.5\n\n93.0\n\n92.6\n\n\n天\u3000\u3000津\n\n99.5\n\n98.0\n\n97.8\n\n秦 皇 岛\n\n99.5\n\n93.7\n\n93.1\n\n\n石 家 庄\n\n99.7\n\n96.7\n\n96.3\n\n包\u3000\u3000头\n\n99.7\n\n93.8\n\n93.6\n\n\n太\u3000\u3000原\n\n100.0\n\n100.9\n\n101.0\n\n丹\u3000\u3000东\n\n99.8\n\n94.9\n\n94.1\n\n\n呼和浩特\n\n99.7\n\n94.1\n\n94.0\n\n锦\u3000\u3000州\n\n99.9\n\n95.6\n\n95.3\n\n\n沈\u3000\u3000阳\n\n100.3\n\n98.0\n\n97.2\n\n吉\u3000\u3000林\n\n100.0\n\n95.9\n\n94.6\n\n\n大\u3000\u3000连\n\n99.6\n\n96.0\n\n95.2\n\n牡 丹 江\n\n100.1\n\n94.4\n\n93.3\n\n\n长\u3000\u3000春\n\n99.3\n\n95.7\n\n95.9\n\n无\u3000\u3000锡\n\n99.6\n\n96.2\n\n96.0\n\n\n哈 尔 滨\n\n99.9\n\n95.2\n\n94.6\n\n徐\u3000\u3000州\n\n99.8\n\n94.8\n\n94.2\n\n\n上\u3000\u3000海\n\n100.7\n\n105.9\n\n105.7\n\n扬\u3000\u3000州\n\n99.1\n\n94.4\n\n93.9\n\n\n南\u3000\u3000京\n\n99.8\n\n99.2\n\n97.4\n\n温\u3000\u3000州\n\n99.8\n\n91.9\n\n91.0\n\n\n杭\u3000\u3000州\n\n100.8\n\n101.6\n\n99.6\n\n金\u3000\u3000华\n\n99.8\n\n93.0\n\n91.3\n\n\n宁\u3000\u3000波\n\n99.9\n\n97.2\n\n94.7\n\n蚌\u3000\u3000埠\n\n99.6\n\n94.3\n\n93.9\n\n\n合\u3000\u3000肥\n\n100.2\n\n96.5\n\n95.3\n\n安\u3000\u3000庆\n\n99.5\n\n94.9\n\n94.4\n\n\n福\u3000\u3000州\n\n99.8\n\n94.4\n\n93.3\n\n泉\u3000\u3000州\n\n99.7\n\n93.8\n\n92.8\n\n\n厦\u3000\u3000门\n\n100.1\n\n96.0\n\n93.9\n\n九\u3000\u3000江\n\n100.2\n\n95.5\n\n93.5\n\n\n南\u3000\u3000昌\n\n99.1\n\n95.1\n\n95.1\n\n赣\u3000\u3000州\n\n100.1\n\n96.2\n\n95.2\n\n\n济\u3000\u3000南\n\n99.7\n\n95.3\n\n94.6\n\n烟\u3000\u3000台\n\n99.9\n\n95.6\n\n94.5\n\n\n青\u3000\u3000岛\n\n100.0\n\n97.3\n\n95.9\n\n济\u3000\u3000宁\n\n99.6\n\n95.7\n\n95.2\n\n\n郑\u3000\u3000州\n\n99.5\n\n96.2\n\n95.4\n\n洛\u3000\u3000阳\n\n99.6\n\n94.3\n\n94.2\n\n\n武\u3000\u3000汉\n\n99.3\n\n95.8\n\n94.3\n\n平 顶 山\n\n99.8\n\n98.9\n\n98.8\n\n\n长\u3000\u3000沙\n\n100.3\n\n96.2\n\n94.5\n\n宜\u3000\u3000昌\n\n99.9\n\n97.6\n\n96.3\n\n\n广\u3000\u3000州\n\n99.2\n\n94.2\n\n92.9\n\n襄\u3000\u3000阳\n\n99.6\n\n95.4\n\n94.5\n\n\n深\u3000\u3000圳\n\n99.6\n\n97.4\n\n96.2\n\n岳\u3000\u3000阳\n\n99.7\n\n93.9\n\n93.7\n\n\n南\u3000\u3000宁\n\n100.4\n\n97.3\n\n94.8\n\n常\u3000\u3000德\n\n99.8\n\n94.7\n\n93.1\n\n\n海\u3000\u3000口\n\n99.3\n\n95.7\n\n96.1\n\n韶\u3000\u3000关\n\n99.9\n\n95.3\n\n94.5\n\n\n重\u3000\u3000庆\n\n99.5\n\n96.8\n\n95.3\n\n湛\u3000\u3000江\n\n99.9\n\n95.9\n\n94.7\n\n\n成\u3000\u3000都\n\n100.1\n\n99.0\n\n97.7\n\n惠\u3000\u3000州\n\n99.7\n\n95.4\n\n94.4\n\n\n贵\u3000\u3000阳\n\n99.6\n\n95.6\n\n95.4\n\n桂\u3000\u3000林\n\n99.6\n\n96.9\n\n96.6\n\n\n昆\u3000\u3000明\n\n99.5\n\n93.2\n\n92.2\n\n北\u3000\u3000海\n\n99.4\n\n93.5\n\n93.9\n\n\n西\u3000\u3000安\n\n99.6\n\n97.0\n\n97.9\n\n三\u3000\u3000亚\n\n100.1\n\n98.2\n\n97.2\n\n\n兰\u3000\u3000州\n\n99.9\n\n92.9\n\n92.6\n\n泸\u3000\u3000州\n\n99.5\n\n93.6\n\n93.0\n\n\n西\u3000\u3000宁\n\n100.0\n\n94.9\n\n94.6\n\n南\u3000\u3000充\n\n99.7\n\n97.0\n\n97.0\n\n\n银\u3000\u3000川\n\n99.7\n\n96.4\n\n95.9\n\n遵\u3000\u3000义\n\n99.8\n\n96.5\n\n96.5\n\n\n乌鲁木齐\n\n100.4\n\n98.5\n\n97.5\n\n大\u3000\u3000理\n\n99.6\n\n93.6\n\n93.5\u2002表2：2025年5月70个大中城市二手住宅销售价格指数\u2002\n\n\n\n城市\n\n环比\n\n同比\n\n1-5月平均\n\n城市\n\n环比\n\n同比\n\n1-5月平均\n\n\n上月=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n上月=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n\n北\u3000\u3000京\n\n99.2\n\n99.3\n\n97.9\n\n唐\u3000\u3000山\n\n99.2\n\n89.5\n\n88.8\n\n\n天\u3000\u3000津\n\n99.4\n\n96.7\n\n95.4\n\n秦 皇 岛\n\n99.1\n\n89.6\n\n89.4\n\n\n石 家 庄\n\n99.6\n\n94.0\n\n93.2\n\n包\u3000\u3000头\n\n99.5\n\n90.3\n\n89.5\n\n\n太\u3000\u3000原\n\n99.6\n\n95.0\n\n95.2\n\n丹\u3000\u3000东\n\n99.6\n\n92.3\n\n90.5\n\n\n呼和浩特\n\n99.4\n\n90.1\n\n89.2\n\n锦\u3000\u3000州\n\n99.6\n\n92.2\n\n91.8\n\n\n沈\u3000\u3000阳\n\n99.8\n\n94.8\n\n93.8\n\n吉\u3000\u3000林\n\n99.7\n\n95.6\n\n94.6\n\n\n大\u3000\u3000连\n\n99.4\n\n92.7\n\n91.6\n\n牡 丹 江\n\n99.9\n\n92.8\n\n92.2\n\n\n长\u3000\u3000春\n\n99.5\n\n93.9\n\n93.6\n\n无\u3000\u3000锡\n\n100.2\n\n94.9\n\n93.5\n\n\n哈 尔 滨\n\n99.4\n\n92.5\n\n92.2\n\n徐\u3000\u3000州\n\n99.5\n\n93.4\n\n92.8\n\n\n上\u3000\u3000海\n\n99.3\n\n99.9\n\n98.7\n\n扬\u3000\u3000州\n\n99.3\n\n91.3\n\n91.3\n\n\n南\u3000\u3000京\n\n99.1\n\n95.4\n\n95.1\n\n温\u3000\u3000州\n\n99.2\n\n91.2\n\n90.2\n\n\n杭\u3000\u3000州\n\n99.6\n\n98.7\n\n97.1\n\n金\u3000\u3000华\n\n99.3\n\n90.8\n\n89.5\n\n\n宁\u3000\u3000波\n\n99.0\n\n93.6\n\n92.5\n\n蚌\u3000\u3000埠\n\n99.5\n\n94.7\n\n93.8\n\n\n合\u3000\u3000肥\n\n99.3\n\n92.7\n\n92.1\n\n安\u3000\u3000庆\n\n99.2\n\n91.9\n\n91.3\n\n\n福\u3000\u3000州\n\n99.4\n\n92.0\n\n91.0\n\n泉\u3000\u3000州\n\n99.6\n\n89.8\n\n89.3\n\n\n厦\u3000\u3000门\n\n99.6\n\n92.8\n\n90.7\n\n九\u3000\u3000江\n\n99.3\n\n92.9\n\n91.7\n\n\n南\u3000\u3000昌\n\n99.3\n\n91.6\n\n90.1\n\n赣\u3000\u3000州\n\n99.6\n\n97.4\n\n95.8\n\n\n济\u3000\u3000南\n\n99.6\n\n92.9\n\n91.3\n\n烟\u3000\u3000台\n\n99.3\n\n92.0\n\n91.2\n\n\n青\u3000\u3000岛\n\n99.8\n\n94.8\n\n93.3\n\n济\u3000\u3000宁\n\n99.4\n\n95.5\n\n94.7\n\n\n郑\u3000\u3000州\n\n99.3\n\n92.1\n\n92.2\n\n洛\u3000\u3000阳\n\n100.1\n\n94.7\n\n93.5\n\n\n武\u3000\u3000汉\n\n99.0\n\n93.0\n\n91.7\n\n平 顶 山\n\n99.7\n\n95.2\n\n94.9\n\n\n长\u3000\u3000沙\n\n99.3\n\n93.1\n\n92.2\n\n宜\u3000\u3000昌\n\n99.6\n\n94.1\n\n93.2\n\n\n广\u3000\u3000州\n\n99.2\n\n93.4\n\n91.5\n\n襄\u3000\u3000阳\n\n99.5\n\n91.7\n\n90.5\n\n\n深\u3000\u3000圳\n\n99.5\n\n96.8\n\n95.5\n\n岳\u3000\u3000阳\n\n99.4\n\n94.1\n\n94.0\n\n\n南\u3000\u3000宁\n\n99.7\n\n92.6\n\n91.5\n\n常\u3000\u3000德\n\n99.3\n\n92.5\n\n91.5\n\n\n海\u3000\u3000口\n\n99.9\n\n95.2\n\n94.0\n\n韶\u3000\u3000关\n\n99.7\n\n93.6\n\n93.3\n\n\n重\u3000\u3000庆\n\n99.9\n\n95.9\n\n95.0\n\n湛\u3000\u3000江\n\n99.5\n\n93.7\n\n92.9\n\n\n成\u3000\u3000都\n\n99.8\n\n98.7\n\n97.0\n\n惠\u3000\u3000州\n\n99.5\n\n90.2\n\n89.7\n\n\n贵\u3000\u3000阳\n\n99.5\n\n95.3\n\n95.0\n\n桂\u3000\u3000林\n\n99.2\n\n95.3\n\n94.9\n\n\n昆\u3000\u3000明\n\n99.4\n\n92.0\n\n92.3\n\n北\u3000\u3000海\n\n99.3\n\n94.5\n\n94.6\n\n\n西\u3000\u3000安\n\n99.3\n\n93.5\n\n93.1\n\n三\u3000\u3000亚\n\n99.4\n\n93.3\n\n93.1\n\n\n兰\u3000\u3000州\n\n99.5\n\n92.4\n\n91.6\n\n泸\u3000\u3000州\n\n99.3\n\n93.5\n\n92.5\n\n\n西\u3000\u3000宁\n\n99.9\n\n94.0\n\n93.0\n\n南\u3000\u3000充\n\n100.1\n\n94.6\n\n93.6\n\n\n银\u3000\u3000川\n\n99.5\n\n95.4\n\n94.7\n\n遵\u3000\u3000义\n\n99.7\n\n94.0\n\n94.2\n\n\n乌鲁木齐\n\n99.8\n\n94.8\n\n94.4\n\n大\u3000\u3000理\n\n99.7\n\n94.2\n\n93.0\u2002表3：2025年5月70个大中城市新建商品住宅销售价格分类指数（一）\u2002\n\n\n\n城市\n\n90m2及以下\n\n90-144m2\n\n144m2以上\n\n\n环比\n\n同比\n\n1-5月\n平均\n\n环比\n\n同比\n\n1-5月\n平均\n\n环比\n\n同比\n\n1-5月\n平均\n\n\n上月\n=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n上月\n=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n上月\n=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n\n北\u3000\u3000京\n\n99.7\n\n95.8\n\n94.1\n\n99.6\n\n95.0\n\n94.9\n\n99.6\n\n96.0\n\n95.1\n\n\n天\u3000\u3000津\n\n99.3\n\n97.8\n\n97.1\n\n99.4\n\n98.1\n\n98.0\n\n99.9\n\n98.0\n\n97.8\n\n\n石 家 庄\n\n99.4\n\n97.0\n\n96.4\n\n99.8\n\n97.0\n\n96.7\n\n99.6\n\n95.7\n\n95.3\n\n\n太\u3000\u3000原\n\n99.8\n\n102.0\n\n101.9\n\n99.9\n\n100.6\n\n100.8\n\n100.1\n\n101.1\n\n101.2\n\n\n呼和浩特\n\n99.8\n\n95.2\n\n95.0\n\n99.6\n\n93.9\n\n93.8\n\n99.8\n\n94.3\n\n94.0\n\n\n沈\u3000\u3000阳\n\n100.2\n\n97.4\n\n96.6\n\n100.1\n\n98.1\n\n97.6\n\n101.1\n\n98.2\n\n97.0\n\n\n大\u3000\u3000连\n\n99.9\n\n98.1\n\n97.0\n\n99.6\n\n95.1\n\n94.5\n\n99.2\n\n95.1\n\n94.3\n\n\n长\u3000\u3000春\n\n99.2\n\n96.3\n\n96.3\n\n99.0\n\n94.6\n\n95.4\n\n99.9\n\n96.6\n\n96.3\n\n\n哈 尔 滨\n\n99.9\n\n94.0\n\n93.4\n\n99.8\n\n96.0\n\n95.2\n\n100.0\n\n94.0\n\n94.0\n\n\n上\u3000\u3000海\n\n100.7\n\n105.3\n\n105.4\n\n100.5\n\n105.1\n\n104.9\n\n100.8\n\n107.3\n\n107.0\n\n\n南\u3000\u3000京\n\n99.8\n\n97.8\n\n96.7\n\n99.8\n\n99.5\n\n97.5\n\n99.9\n\n99.3\n\n97.7\n\n\n杭\u3000\u3000州\n\n100.7\n\n100.3\n\n98.7\n\n101.0\n\n102.2\n\n100.0\n\n100.6\n\n100.9\n\n99.4\n\n\n宁\u3000\u3000波\n\n99.9\n\n98.3\n\n96.2\n\n99.9\n\n97.7\n\n95.2\n\n100.0\n\n95.7\n\n93.0\n\n\n合\u3000\u3000肥\n\n100.3\n\n96.4\n\n94.6\n\n100.2\n\n96.7\n\n95.5\n\n100.2\n\n96.2\n\n95.1\n\n\n福\u3000\u3000州\n\n99.7\n\n94.5\n\n93.3\n\n99.7\n\n94.4\n\n93.4\n\n99.9\n\n94.4\n\n92.9\n\n\n厦\u3000\u3000门\n\n100.4\n\n96.8\n\n94.1\n\n100.0\n\n96.8\n\n94.6\n\n100.1\n\n94.4\n\n92.6\n\n\n南\u3000\u3000昌\n\n99.7\n\n95.6\n\n95.3\n\n99.0\n\n95.1\n\n95.1\n\n98.9\n\n95.0\n\n95.4\n\n\n济\u3000\u3000南\n\n99.9\n\n94.1\n\n92.5\n\n99.6\n\n95.2\n\n94.8\n\n99.9\n\n96.0\n\n95.2\n\n\n青\u3000\u3000岛\n\n99.9\n\n97.2\n\n95.8\n\n100.1\n\n96.9\n\n95.4\n\n99.9\n\n98.3\n\n97.2\n\n\n郑\u3000\u3000州\n\n99.2\n\n94.6\n\n93.9\n\n99.6\n\n96.5\n\n95.4\n\n99.4\n\n97.1\n\n96.9\n\n\n武\u3000\u3000汉\n\n99.6\n\n96.3\n\n94.4\n\n99.2\n\n95.8\n\n94.3\n\n99.5\n\n95.4\n\n94.3\n\n\n长\u3000\u3000沙\n\n100.0\n\n96.7\n\n94.1\n\n100.3\n\n96.4\n\n94.8\n\n100.3\n\n95.4\n\n93.7\n\n\n广\u3000\u3000州\n\n99.0\n\n94.4\n\n92.9\n\n99.3\n\n94.1\n\n92.6\n\n98.8\n\n94.4\n\n94.3\n\n\n深\u3000\u3000圳\n\n99.8\n\n97.9\n\n96.3\n\n99.4\n\n97.3\n\n96.3\n\n100.0\n\n97.3\n\n95.8\n\n\n南\u3000\u3000宁\n\n100.2\n\n97.6\n\n95.3\n\n100.5\n\n97.2\n\n94.6\n\n100.0\n\n97.5\n\n95.4\n\n\n海\u3000\u3000口\n\n98.8\n\n96.2\n\n96.8\n\n99.4\n\n95.5\n\n95.8\n\n99.1\n\n96.0\n\n96.3\n\n\n重\u3000\u3000庆\n\n99.7\n\n96.7\n\n95.3\n\n99.3\n\n96.9\n\n95.5\n\n99.6\n\n96.7\n\n95.0\n\n\n成\u3000\u3000都\n\n100.3\n\n98.6\n\n97.6\n\n100.3\n\n99.3\n\n98.0\n\n99.8\n\n98.8\n\n97.2\n\n\n贵\u3000\u3000阳\n\n99.5\n\n94.6\n\n94.4\n\n99.8\n\n95.5\n\n95.3\n\n99.3\n\n96.4\n\n96.2\n\n\n昆\u3000\u3000明\n\n99.3\n\n93.4\n\n92.5\n\n99.5\n\n93.2\n\n92.2\n\n99.6\n\n93.1\n\n92.2\n\n\n西\u3000\u3000安\n\n99.5\n\n97.1\n\n97.9\n\n99.6\n\n97.0\n\n97.9\n\n99.7\n\n97.0\n\n97.8\n\n\n兰\u3000\u3000州\n\n99.9\n\n92.2\n\n92.7\n\n99.8\n\n93.2\n\n92.8\n\n99.9\n\n91.7\n\n91.3\n\n\n西\u3000\u3000宁\n\n99.9\n\n95.6\n\n95.1\n\n100.0\n\n94.9\n\n94.6\n\n100.1\n\n94.7\n\n94.4\n\n\n银\u3000\u3000川\n\n99.6\n\n97.6\n\n97.6\n\n99.7\n\n96.3\n\n95.8\n\n99.9\n\n96.2\n\n95.3\n\n\n乌鲁木齐\n\n100.3\n\n97.7\n\n96.5\n\n100.5\n\n98.9\n\n97.8\n\n100.0\n\n97.8\n\n96.8\u2002表3：2025年5月70个大中城市新建商品住宅销售价格分类指数（二）\u2002\n\n\n\n城市\n\n90m2及以下\n\n90-144m2\n\n144m2以上\n\n\n环比\n\n同比\n\n1-5月\n平均\n\n环比\n\n同比\n\n1-5月\n平均\n\n环比\n\n同比\n\n1-5月\n平均\n\n\n上月\n=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n上月\n=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n上月=\n100\n\n上年同月\n=100\n\n上年同期\n=100\n\n\n唐\u3000\u3000山\n\n99.3\n\n92.4\n\n92.3\n\n99.5\n\n93.1\n\n92.6\n\n99.4\n\n92.6\n\n92.4\n\n\n秦 皇 岛\n\n99.4\n\n93.9\n\n93.0\n\n99.7\n\n94.1\n\n93.4\n\n99.2\n\n92.3\n\n92.1\n\n\n包\u3000\u3000头\n\n99.7\n\n95.0\n\n95.1\n\n99.6\n\n93.6\n\n93.3\n\n99.8\n\n93.9\n\n93.8\n\n\n丹\u3000\u3000东\n\n99.7\n\n94.4\n\n94.1\n\n99.9\n\n95.2\n\n93.8\n\n99.8\n\n94.5\n\n94.7\n\n\n锦\u3000\u3000州\n\n99.8\n\n94.6\n\n93.5\n\n100.0\n\n96.5\n\n96.4\n\n99.8\n\n94.0\n\n94.4\n\n\n吉\u3000\u3000林\n\n99.8\n\n95.0\n\n93.8\n\n100.0\n\n96.1\n\n94.6\n\n99.9\n\n96.7\n\n95.8\n\n\n牡 丹 江\n\n100.0\n\n94.3\n\n93.9\n\n100.1\n\n94.5\n\n93.1\n\n99.8\n\n94.3\n\n92.3\n\n\n无\u3000\u3000锡\n\n99.9\n\n96.4\n\n95.8\n\n99.4\n\n96.3\n\n96.3\n\n99.9\n\n95.9\n\n94.9\n\n\n徐\u3000\u3000州\n\n100.0\n\n94.5\n\n93.2\n\n99.8\n\n95.0\n\n94.5\n\n99.9\n\n93.7\n\n93.0\n\n\n扬\u3000\u3000州\n\n99.3\n\n94.0\n\n93.3\n\n99.1\n\n94.4\n\n93.8\n\n98.9\n\n94.6\n\n94.3\n\n\n温\u3000\u3000州\n\n99.8\n\n92.0\n\n90.9\n\n99.7\n\n92.3\n\n91.4\n\n99.8\n\n91.0\n\n90.1\n\n\n金\u3000\u3000华\n\n99.9\n\n92.6\n\n91.1\n\n99.7\n\n93.1\n\n91.1\n\n99.7\n\n93.2\n\n92.2\n\n\n蚌\u3000\u3000埠\n\n99.7\n\n95.1\n\n94.9\n\n99.6\n\n94.2\n\n93.6\n\n99.2\n\n93.8\n\n94.5\n\n\n安\u3000\u3000庆\n\n99.8\n\n96.0\n\n96.3\n\n99.4\n\n94.9\n\n94.1\n\n99.7\n\n94.2\n\n94.0\n\n\n泉\u3000\u3000州\n\n99.6\n\n94.5\n\n93.3\n\n99.6\n\n93.6\n\n92.5\n\n99.9\n\n94.1\n\n93.3\n\n\n九\u3000\u3000江\n\n100.1\n\n95.1\n\n93.3\n\n100.2\n\n95.8\n\n93.8\n\n100.6\n\n94.6\n\n92.7\n\n\n赣\u3000\u3000州\n\n100.0\n\n96.0\n\n94.6\n\n100.1\n\n96.1\n\n95.3\n\n100.1\n\n96.5\n\n95.5\n\n\n烟\u3000\u3000台\n\n99.9\n\n94.9\n\n93.0\n\n100.0\n\n95.8\n\n94.9\n\n99.6\n\n95.3\n\n93.8\n\n\n济\u3000\u3000宁\n\n99.9\n\n95.4\n\n94.1\n\n99.4\n\n96.4\n\n96.1\n\n99.8\n\n94.3\n\n93.6\n\n\n洛\u3000\u3000阳\n\n99.3\n\n94.6\n\n95.1\n\n99.7\n\n94.4\n\n94.2\n\n99.5\n\n93.7\n\n93.7\n\n\n平 顶 山\n\n100.0\n\n99.6\n\n99.0\n\n99.8\n\n98.8\n\n98.7\n\n99.9\n\n99.2\n\n99.1\n\n\n宜\u3000\u3000昌\n\n100.0\n\n97.3\n\n96.7\n\n99.9\n\n98.0\n\n96.6\n\n99.8\n\n95.7\n\n94.5\n\n\n襄\u3000\u3000阳\n\n99.9\n\n96.3\n\n95.4\n\n99.6\n\n95.5\n\n94.5\n\n99.4\n\n94.0\n\n93.6\n\n\n岳\u3000\u3000阳\n\n99.5\n\n93.1\n\n92.7\n\n99.7\n\n93.8\n\n93.9\n\n99.8\n\n94.7\n\n94.4\n\n\n常\u3000\u3000德\n\n99.5\n\n94.1\n\n92.7\n\n99.9\n\n94.9\n\n93.3\n\n99.9\n\n94.2\n\n92.3\n\n\n韶\u3000\u3000关\n\n99.5\n\n95.1\n\n95.7\n\n100.0\n\n95.6\n\n94.6\n\n99.5\n\n94.2\n\n93.9\n\n\n湛\u3000\u3000江\n\n99.8\n\n95.6\n\n94.2\n\n100.0\n\n96.0\n\n94.8\n\n99.7\n\n96.0\n\n94.4\n\n\n惠\u3000\u3000州\n\n99.6\n\n95.5\n\n94.1\n\n99.8\n\n95.5\n\n94.6\n\n99.6\n\n94.5\n\n93.8\n\n\n桂\u3000\u3000林\n\n99.4\n\n97.3\n\n97.3\n\n99.7\n\n96.7\n\n96.3\n\n99.4\n\n97.9\n\n97.2\n\n\n北\u3000\u3000海\n\n99.3\n\n93.8\n\n94.2\n\n99.5\n\n93.1\n\n93.5\n\n99.1\n\n93.5\n\n93.7\n\n\n三\u3000\u3000亚\n\n100.0\n\n98.2\n\n97.7\n\n100.2\n\n98.1\n\n96.8\n\n99.9\n\n98.6\n\n97.7\n\n\n泸\u3000\u3000州\n\n99.4\n\n94.5\n\n93.7\n\n99.5\n\n93.3\n\n92.9\n\n99.6\n\n93.8\n\n92.9\n\n\n南\u3000\u3000充\n\n99.8\n\n96.6\n\n96.6\n\n99.6\n\n97.0\n\n97.2\n\n99.8\n\n98.0\n\n96.9\n\n\n遵\u3000\u3000义\n\n99.8\n\n96.7\n\n96.5\n\n99.8\n\n96.6\n\n96.6\n\n99.6\n\n96.2\n\n96.1\n\n\n大\u3000\u3000理\n\n99.6\n\n92.3\n\n91.9\n\n99.5\n\n94.0\n\n94.3\n\n99.9\n\n93.5\n\n92.8\u2002表4：2025年5月70个大中城市二手住宅销售价格分类指数（一）\u2002\n\n\n\n城市\n\n90m2及以下\n\n90-144m2\n\n144m2以上\n\n\n环比\n\n同比\n\n1-5月\n平均\n\n环比\n\n同比\n\n1-5月\n平均\n\n环比\n\n同比\n\n1-5月\n平均\n\n\n上月\n=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n上月\n=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n上月\n=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n\n北\u3000\u3000京\n\n98.9\n\n99.8\n\n98.0\n\n99.1\n\n98.6\n\n97.6\n\n99.8\n\n99.2\n\n98.1\n\n\n天\u3000\u3000津\n\n99.6\n\n97.0\n\n95.3\n\n99.1\n\n96.1\n\n95.2\n\n99.2\n\n97.3\n\n96.5\n\n\n石 家 庄\n\n99.5\n\n93.5\n\n92.9\n\n99.7\n\n94.7\n\n93.6\n\n99.4\n\n93.6\n\n92.9\n\n\n太\u3000\u3000原\n\n99.7\n\n95.3\n\n95.5\n\n99.5\n\n95.1\n\n95.3\n\n99.7\n\n93.8\n\n94.3\n\n\n呼和浩特\n\n99.6\n\n90.5\n\n89.3\n\n99.1\n\n89.9\n\n89.3\n\n99.6\n\n89.2\n\n88.5\n\n\n沈\u3000\u3000阳\n\n99.9\n\n94.6\n\n93.4\n\n99.6\n\n95.8\n\n95.1\n\n99.7\n\n93.0\n\n92.2\n\n\n大\u3000\u3000连\n\n99.4\n\n93.9\n\n92.6\n\n99.4\n\n91.0\n\n90.3\n\n99.6\n\n91.1\n\n90.1\n\n\n长\u3000\u3000春\n\n99.4\n\n93.0\n\n92.8\n\n99.8\n\n95.4\n\n94.8\n\n99.4\n\n93.8\n\n93.8\n\n\n哈 尔 滨\n\n99.4\n\n91.9\n\n91.4\n\n99.6\n\n93.1\n\n92.9\n\n98.9\n\n92.6\n\n92.7\n\n\n上\u3000\u3000海\n\n99.1\n\n99.4\n\n97.9\n\n99.4\n\n100.4\n\n99.5\n\n99.5\n\n100.7\n\n99.4\n\n\n南\u3000\u3000京\n\n99.2\n\n95.8\n\n95.1\n\n99.0\n\n95.2\n\n94.9\n\n99.1\n\n94.8\n\n95.5\n\n\n杭\u3000\u3000州\n\n99.7\n\n98.7\n\n97.0\n\n99.4\n\n99.4\n\n97.7\n\n99.8\n\n97.4\n\n96.1\n\n\n宁\u3000\u3000波\n\n99.1\n\n93.7\n\n92.5\n\n99.0\n\n93.0\n\n92.4\n\n99.0\n\n95.2\n\n93.3\n\n\n合\u3000\u3000肥\n\n99.1\n\n92.0\n\n91.5\n\n99.3\n\n93.1\n\n92.3\n\n99.8\n\n94.3\n\n93.2\n\n\n福\u3000\u3000州\n\n99.5\n\n91.0\n\n90.4\n\n99.2\n\n92.7\n\n91.6\n\n99.6\n\n92.4\n\n91.1\n\n\n厦\u3000\u3000门\n\n99.6\n\n92.5\n\n90.4\n\n99.5\n\n93.0\n\n90.6\n\n99.6\n\n93.0\n\n91.4\n\n\n南\u3000\u3000昌\n\n98.9\n\n91.1\n\n90.0\n\n99.5\n\n92.1\n\n90.4\n\n98.9\n\n90.8\n\n89.4\n\n\n济\u3000\u3000南\n\n99.2\n\n92.4\n\n91.3\n\n99.7\n\n92.9\n\n91.2\n\n99.9\n\n93.4\n\n91.7\n\n\n青\u3000\u3000岛\n\n99.8\n\n94.6\n\n92.9\n\n99.7\n\n95.1\n\n93.6\n\n99.9\n\n94.6\n\n93.7\n\n\n郑\u3000\u3000州\n\n99.5\n\n91.6\n\n91.2\n\n98.9\n\n92.6\n\n93.0\n\n99.7\n\n92.3\n\n92.5\n\n\n武\u3000\u3000汉\n\n99.1\n\n93.6\n\n92.1\n\n98.8\n\n92.3\n\n91.2\n\n99.3\n\n93.5\n\n92.1\n\n\n长\u3000\u3000沙\n\n99.3\n\n92.9\n\n91.9\n\n99.1\n\n93.2\n\n92.5\n\n99.9\n\n93.3\n\n92.0\n\n\n广\u3000\u3000州\n\n99.1\n\n93.7\n\n91.7\n\n99.5\n\n92.8\n\n91.1\n\n98.8\n\n93.7\n\n92.2\n\n\n深\u3000\u3000圳\n\n99.6\n\n96.6\n\n95.2\n\n99.5\n\n97.1\n\n96.0\n\n99.4\n\n96.7\n\n95.6\n\n\n南\u3000\u3000宁\n\n99.5\n\n92.2\n\n91.1\n\n99.9\n\n92.9\n\n91.8\n\n99.7\n\n92.6\n\n91.6\n\n\n海\u3000\u3000口\n\n100.1\n\n94.7\n\n93.6\n\n99.8\n\n95.5\n\n94.5\n\n99.8\n\n95.0\n\n93.4\n\n\n重\u3000\u3000庆\n\n99.7\n\n95.4\n\n94.5\n\n100.2\n\n96.6\n\n95.4\n\n99.8\n\n96.0\n\n95.4\n\n\n成\u3000\u3000都\n\n99.7\n\n98.3\n\n97.0\n\n99.8\n\n99.4\n\n96.9\n\n100.1\n\n98.8\n\n96.9\n\n\n贵\u3000\u3000阳\n\n99.7\n\n94.1\n\n93.5\n\n99.4\n\n96.0\n\n96.0\n\n99.3\n\n95.1\n\n94.7\n\n\n昆\u3000\u3000明\n\n99.2\n\n92.1\n\n92.1\n\n99.5\n\n92.4\n\n92.5\n\n99.6\n\n91.5\n\n92.1\n\n\n西\u3000\u3000安\n\n99.2\n\n94.0\n\n93.6\n\n99.1\n\n93.4\n\n93.1\n\n99.9\n\n92.7\n\n92.2\n\n\n兰\u3000\u3000州\n\n99.9\n\n92.1\n\n90.2\n\n99.0\n\n92.8\n\n93.0\n\n99.2\n\n92.1\n\n92.2\n\n\n西\u3000\u3000宁\n\n99.9\n\n93.2\n\n92.3\n\n99.9\n\n94.3\n\n93.3\n\n99.7\n\n94.6\n\n94.0\n\n\n银\u3000\u3000川\n\n99.8\n\n95.2\n\n94.2\n\n99.3\n\n95.8\n\n95.2\n\n99.8\n\n94.7\n\n93.8\n\n\n乌鲁木齐\n\n99.9\n\n94.8\n\n94.3\n\n99.7\n\n94.5\n\n94.3\n\n99.9\n\n96.4\n\n95.5\u2002表4：2025年5月70个大中城市二手住宅销售价格分类指数（二）\u2002\n\n\n\n城市\n\n90m2及以下\n\n90-144m2\n\n144m2以上\n\n\n环比\n\n同比\n\n1-5月\n平均\n\n环比\n\n同比\n\n1-5月\n平均\n\n环比\n\n同比\n\n1-5月\n平均\n\n\n上月\n=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n上月\n=100\n\n上年同月=100\n\n上年同期\n=100\n\n上月\n=100\n\n上年同月\n=100\n\n上年同期\n=100\n\n\n唐\u3000\u3000山\n\n99.3\n\n89.6\n\n88.7\n\n99.0\n\n89.5\n\n88.9\n\n99.5\n\n89.7\n\n89.3\n\n\n秦 皇 岛\n\n99.1\n\n89.1\n\n89.1\n\n99.1\n\n90.0\n\n89.6\n\n99.0\n\n90.8\n\n90.6\n\n\n包\u3000\u3000头\n\n99.8\n\n89.9\n\n89.1\n\n99.4\n\n90.5\n\n89.7\n\n99.1\n\n91.4\n\n90.6\n\n\n丹\u3000\u3000东\n\n99.7\n\n92.2\n\n90.5\n\n99.7\n\n92.0\n\n90.0\n\n99.3\n\n93.6\n\n92.3\n\n\n锦\u3000\u3000州\n\n99.9\n\n92.4\n\n91.8\n\n99.4\n\n91.6\n\n91.2\n\n99.6\n\n94.1\n\n94.3\n\n\n吉\u3000\u3000林\n\n99.8\n\n95.7\n\n94.7\n\n99.8\n\n95.5\n\n94.3\n\n99.5\n\n95.5\n\n95.4\n\n\n牡 丹 江\n\n99.8\n\n92.6\n\n91.8\n\n100.1\n\n93.1\n\n93.1\n\n99.8\n\n92.0\n\n91.7\n\n\n无\u3000\u3000锡\n\n100.0\n\n94.3\n\n93.1\n\n100.2\n\n95.6\n\n94.0\n\n100.5\n\n94.3\n\n92.9\n\n\n徐\u3000\u3000州\n\n99.9\n\n92.6\n\n92.1\n\n99.4\n\n93.6\n\n93.1\n\n99.0\n\n95.0\n\n93.9\n\n\n扬\u3000\u3000州\n\n99.4\n\n91.8\n\n91.7\n\n99.1\n\n91.0\n\n91.3\n\n99.6\n\n90.2\n\n90.1\n\n\n温\u3000\u3000州\n\n99.2\n\n91.4\n\n90.6\n\n99.0\n\n91.5\n\n90.1\n\n99.4\n\n90.6\n\n89.7\n\n\n金\u3000\u3000华\n\n99.1\n\n90.7\n\n89.4\n\n99.4\n\n91.6\n\n90.0\n\n99.6\n\n89.5\n\n88.7\n\n\n蚌\u3000\u3000埠\n\n99.7\n\n94.8\n\n93.4\n\n99.5\n\n94.8\n\n94.1\n\n99.6\n\n93.6\n\n93.0\n\n\n安\u3000\u3000庆\n\n99.4\n\n92.1\n\n91.4\n\n99.1\n\n91.9\n\n91.5\n\n99.2\n\n90.8\n\n90.0\n\n\n泉\u3000\u3000州\n\n99.4\n\n90.0\n\n89.9\n\n99.6\n\n89.2\n\n88.4\n\n99.8\n\n90.5\n\n89.9\n\n\n九\u3000\u3000江\n\n99.7\n\n92.9\n\n91.4\n\n99.0\n\n93.0\n\n91.9\n\n99.3\n\n92.3\n\n91.3\n\n\n赣\u3000\u3000州\n\n99.6\n\n97.2\n\n95.4\n\n99.7\n\n97.6\n\n96.1\n\n99.5\n\n96.7\n\n95.3\n\n\n烟\u3000\u3000台\n\n99.1\n\n91.1\n\n90.2\n\n99.6\n\n92.9\n\n92.3\n\n99.3\n\n92.7\n\n91.5\n\n\n济\u3000\u3000宁\n\n98.8\n\n94.1\n\n93.9\n\n99.6\n\n96.3\n\n95.1\n\n99.7\n\n95.6\n\n95.1\n\n\n洛\u3000\u3000阳\n\n100.1\n\n95.1\n\n93.7\n\n100.0\n\n94.6\n\n93.6\n\n100.3\n\n94.3\n\n93.0\n\n\n平 顶 山\n\n99.8\n\n94.5\n\n94.2\n\n99.7\n\n95.7\n\n95.4\n\n99.5\n\n95.3\n\n94.6\n\n\n宜\u3000\u3000昌\n\n99.2\n\n93.2\n\n92.7\n\n99.8\n\n94.8\n\n93.6\n\n99.7\n\n93.7\n\n92.6\n\n\n襄\u3000\u3000阳\n\n99.5\n\n90.9\n\n90.0\n\n99.5\n\n91.6\n\n90.4\n\n99.4\n\n93.9\n\n92.4\n\n\n岳\u3000\u3000阳\n\n99.3\n\n94.3\n\n94.1\n\n99.4\n\n94.2\n\n94.0\n\n99.4\n\n93.9\n\n94.0\n\n\n常\u3000\u3000德\n\n99.4\n\n92.2\n\n91.2\n\n99.2\n\n92.4\n\n91.6\n\n99.4\n\n92.8\n\n91.7\n\n\n韶\u3000\u3000关\n\n99.9\n\n94.1\n\n93.2\n\n99.8\n\n93.2\n\n93.1\n\n99.7\n\n94.0\n\n93.8\n\n\n湛\u3000\u3000江\n\n99.2\n\n93.2\n\n92.9\n\n99.7\n\n94.2\n\n93.0\n\n99.5\n\n93.5\n\n92.9\n\n\n惠\u3000\u3000州\n\n99.7\n\n90.9\n\n90.0\n\n99.4\n\n90.2\n\n89.9\n\n99.5\n\n89.3\n\n89.1\n\n\n桂\u3000\u3000林\n\n99.1\n\n95.2\n\n95.3\n\n99.3\n\n95.5\n\n94.9\n\n99.2\n\n95.0\n\n94.1\n\n\n北\u3000\u3000海\n\n99.4\n\n94.7\n\n94.9\n\n99.2\n\n93.7\n\n94.0\n\n99.4\n\n95.0\n\n94.9\n\n\n三\u3000\u3000亚\n\n99.6\n\n93.3\n\n93.0\n\n99.2\n\n94.0\n\n93.4\n\n99.4\n\n92.2\n\n92.9\n\n\n泸\u3000\u3000州\n\n99.3\n\n92.7\n\n92.4\n\n99.3\n\n93.8\n\n92.6\n\n99.6\n\n93.7\n\n92.5\n\n\n南\u3000\u3000充\n\n100.0\n\n95.0\n\n93

In [22]:
# 只处理第一个表格
if tables:
    table = tables[0]
    rows = table.find_all('tr')
    city_list = []
    values = []
    for row in rows[2:]:  # 跳过前两行表头
        cols = row.find_all(['td', 'th'])
        # 每行有8列，前4列为城市1，后4列为城市2
        if len(cols) == 8:
            # 城市1
            city1 = replace_empty(cols[0].get_text(strip=True))
            factor1 = cols[1].get_text(strip=True)
            # print(replace_empty(city1))
            each_dict[city1] = factor1

In [1]:
all_data[time_str]=each_dict
# all_data

NameError: name 'each_dict' is not defined

In [3]:
all_data = dump_pickle("data.pkl")

# print(len(all_data))

all_data = dict(sorted(all_data.items()))

# print(all_data.keys())

after_cal = []
col_names = []
# print((all_data))
for k,v in all_data.items():
    # print(k,v)
    col_names=list(v.keys())
    break

In [4]:
all_data["201805"]

{'北京': '100.2',
 '唐山': '100.3',
 '天津': '100.5',
 '秦皇岛': '100.6',
 '石家庄': '101.2',
 '包头': '100.8',
 '太原': '100.7',
 '丹东': '105.3',
 '呼和浩特': '101.6',
 '锦州': '100.3',
 '沈阳': '101.7',
 '吉林': '100.4',
 '大连': '101.7',
 '牡丹江': '100.0',
 '长春': '101.3',
 '无锡': '99.9',
 '哈尔滨': '101.2',
 '扬州': '100.6',
 '上海': '99.8',
 '徐州': '101.3',
 '南京': '99.8',
 '温州': '100.1',
 '杭州': '100.0',
 '金华': '100.6',
 '宁波': '100.5',
 '蚌埠': '100.2',
 '合肥': '100.2',
 '安庆': '99.9',
 '福州': '98.9',
 '泉州': '99.9',
 '厦门': '101.1',
 '九江': '100.8',
 '南昌': '100.7',
 '赣州': '100.4',
 '济南': '100.4',
 '烟台': '100.8',
 '青岛': '102.0',
 '济宁': '100.8',
 '郑州': '101.6',
 '洛阳': '100.4',
 '武汉': '101.1',
 '平顶山': '100.8',
 '长沙': '101.6',
 '宜昌': '100.8',
 '广州': '101.8',
 '襄阳': '100.1',
 '深圳': '99.9',
 '岳阳': '101.0',
 '南宁': '100.3',
 '常德': '100.7',
 '海口': '102.1',
 '惠州': '100.3',
 '重庆': '100.9',
 '湛江': '100.1',
 '成都': '102.1',
 '韶关': '100.5',
 '贵阳': '100.6',
 '桂林': '100.6',
 '昆明': '100.9',
 '北海': '101.1',
 '西安': '101.6',
 '三亚': '102.4',
 '兰州': '100.7',
 '泸州': '100.7',
 '西宁': '100.1',
 '南充': '101.4',
 '银川': '100.4',
 '遵义': '100.7',
 '乌鲁木齐': '101.2',
 '大理': '100.8'}

In [5]:
all_data
# 直接用 DataFrame.from_dict，orient='index'，然后重置索引
df = pd.DataFrame.from_dict(all_data, orient='index')
df.index.name = '时间'
df = df.reset_index()

In [6]:
df

,时间,北京,唐山,天津,秦皇岛,石家庄,包头,太原,丹东,呼和浩特,...,西安,三亚,兰州,泸州,西宁,南充,银川,遵义,乌鲁木齐,大理
0,201801,100.2,100.7,100.5,100.8,100.1,100.8,100.5,100.1,100.1,...,100.6,100.9,100.4,100.8,100.2,100.3,100.4,101.1,100.4,100.7
1,201802,99.7,100.2,100.1,100.6,100.1,100.4,100.0,99.8,100.5,...,100.5,101.0,100.5,100.4,100.7,101.7,100.5,100.6,101.3,100.9
2,201803,100.1,100.8,100.0,101.4,100.7,100.6,100.6,100.4,100.5,...,100.9,100.7,100.4,100.3,100.0,100.6,100.8,100.9,100.8,100.9
3,201804,100.2,100.7,100.1,100.7,100.3,100.6,101.4,102.0,101.0,...,101.6,101.9,100.5,100.4,99.8,101.0,100.6,100.8,101.1,101.2
4,201805,100.2,100.3,100.5,100.6,101.2,100.8,100.7,105.3,101.6,...,101.6,102.4,100.7,100.7,100.1,101.4,100.4,100.7,101.2,100.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,202502,100.1,99.5,99.7,99.8,99.7,99.6,100.1,99.6,99.4,...,99.5,99.9,99.8,99.6,99.9,99.8,99.4,99.6,99.9,99.8
86,202503,99.8,99.7,100.3,99.5,99.9,99.4,100.2,99.3,99.5,...,99.8,99.8,99.5,99.8,99.5,99.9,100.1,100.1,100.1,99.7
87,202504,100.1,99.6,100.4,99.7,99.8,99.6,100.3,99.9,99.8,...,99.7,100.2,99.6,99.6,99.7,99.8,99.4,100.2,100.3,99.4
88,202505,99.6,99.5,99.5,99.5,99.7,99.7,100.0,99.8,99.7,...,99.6,100.1,99.9,99.5,100.0,99.7,99.7,99.8,100.4,99.6
89,202506,99.7,99.3,99.8,99.4,99.8,99.5,100.1,100.1,99.9,...,99.5,100.1,99.8,99.7,99.8,99.4,99.9,99.6,100.2,99.7

In [7]:
df = df.map(lambda x: pd.to_numeric(x, errors='coerce'))

In [54]:
df[df["时间"]=="202204"]["唐山"]

Series([], Name: 唐山, dtype: float64)

In [31]:
len(df[df["呼和浩特"]<100])

38

In [32]:
len(df[df["呼和浩特"]>100])

47

In [33]:
len(df[df["呼和浩特"]==100])

5

In [30]:
df["呼和浩特"].min()

98.6

In [39]:
(df["韶关"].sort_values( ascending=True))

69     98.9
45     98.9
79     99.0
51     99.0
78     99.1
      ...
64    100.7
18    100.8
41    100.8
16    101.2
7     101.4
Name: 韶关, Length: 90, dtype: float64

In [ ]:
df.sort_values(by="韶关", ascending=True)

In [9]:
print(df[["唐山","时间"]])

       唐山      时间
0   100.7  201801
1   100.2  201802
2   100.8  201803
3   100.7  201804
4   100.3  201805
..    ...     ...
85   99.5  202502
86   99.7  202503
87   99.6  202504
88   99.5  202505
89   99.3  202506

[90 rows x 2 columns]

In [25]:
df.to_csv('house_price_origin.csv', index=False)

In [65]:
df[df["时间"]==202301]

Empty DataFrame
Columns: [时间, 北京, 唐山, 天津, 秦皇岛, 石家庄, 包头, 太原, 丹东, 呼和浩特, 锦州, 沈阳, 吉林, 大连, 牡丹江, 长春, 无锡, 哈尔滨, 扬州, 上海, 徐州, 南京, 温州, 杭州, 金华, 宁波, 蚌埠, 合肥, 安庆, 福州, 泉州, 厦门, 九江, 南昌, 赣州, 济南, 烟台, 青岛, 济宁, 郑州, 洛阳, 武汉, 平顶山, 长沙, 宜昌, 广州, 襄阳, 深圳, 岳阳, 南宁, 常德, 海口, 惠州, 重庆, 湛江, 成都, 韶关, 贵阳, 桂林, 昆明, 北海, 西安, 三亚, 兰州, 泸州, 西宁, 南充, 银川, 遵义, 乌鲁木齐, 大理]
Index: []

[0 rows x 71 columns]

In [13]:
df[df["时间"]>202301][["时间","呼和浩特"]]

        时间   呼和浩特
61  202302  100.6
62  202303  100.5
63  202304  100.3
64  202305  100.1
65  202306  100.2
66  202307   99.9
67  202308   99.9
68  202309   99.7
69  202310   99.8
70  202311   99.6
71  202312   99.7
72  202401   99.3
73  202402   99.7
74  202403   99.6
75  202404   99.5
76  202405   99.5
77  202406   99.4
78  202407   99.9
79  202408   99.6
80  202409   99.4
81  202410   99.2
82  202411   99.3
83  202412   99.2
84  202501   99.4
85  202502   99.4
86  202503   99.5
87  202504   99.8
88  202505   99.7
89  202506   99.9

In [52]:
df[df["时间"]>202301][["时间","韶关"]]

        时间     韶关
61  202302  100.2
62  202303  100.6
63  202304  100.4
64  202305  100.7
65  202306   99.7
66  202307   99.7
67  202308   99.5
68  202309   99.3
69  202310   98.9
70  202311   99.2
71  202312   99.4
72  202401   99.6
73  202402   99.4
74  202403   99.7
75  202404   99.5
76  202405   99.1
77  202406  100.0
78  202407   99.1
79  202408   99.0
80  202409   99.7
81  202410   99.7
82  202411   99.5
83  202412   99.4
84  202501   99.7
85  202502   99.4
86  202503  100.0
87  202504   99.7
88  202505   99.9
89  202506   99.8

In [14]:
# for i, row in df.iterrows():
#     print(row)

In [ ]:
df[df["时间"]>2020]

In [63]:
city_cols = [col for col in df.columns if col != '时间']
startdate = 201712
df2=df[df["时间"]>startdate]
# 新建结果 DataFrame，第一行全是 100
result = pd.DataFrame(columns=df2.columns)
first_row = [str(startdate)] + [100.0] * len(city_cols)
result.loc[0] = first_row

# 依次计算后续行
for i, row in df2.iterrows():
    prev = result.iloc[-1, 1:].astype(float)  # 上一行的城市数据
    curr = row[city_cols].astype(float)      # 当前行的指数
    new_row = [row['时间']] + list(prev.values * curr.values / 100)
    result.loc[len(result)] = new_row

# 重置索引
result = result.reset_index(drop=True)
result.to_csv("processed.csv",index=False, encoding='utf-8-sig')
# print(result)

In [64]:
result[["时间","西安"]].iloc[:30]

          时间          西安
0     201712  100.000000
1   201801.0  100.600000
2   201802.0  101.103000
3   201803.0  102.012927
4   201804.0  103.645134
5   201805.0  105.303456
6   201806.0  106.461794
7   201807.0  107.739336
8   201808.0  110.971516
9   201809.0  117.851750
10  201810.0  119.383822
11  201811.0  121.055196
12  201812.0  122.386803
13  201901.0  124.222605
14  201902.0  125.589054
15  201903.0  126.844944
16  201904.0  128.240239
17  201905.0  130.805043
18  201906.0  133.028729
19  201907.0  134.891131
20  201908.0  135.565587
21  201909.0  136.514546
22  201910.0  137.743177
23  201911.0  138.707379
24  201912.0  139.678331
25  202001.0  140.097366
26  202002.0  140.097366
27  202003.0  140.797853
28  202004.0  141.642640
29  202005.0  142.350853

In [59]:
city_cols = [col for col in df.columns if col != '时间']
startdate = 202212
df2=df[df["时间"]>startdate]
# 新建结果 DataFrame，第一行全是 100
result = pd.DataFrame(columns=df2.columns)
first_row = [str(startdate)] + [100.0] * len(city_cols)
result.loc[0] = first_row

# 依次计算后续行
for i, row in df2.iterrows():
    prev = result.iloc[-1, 1:].astype(float)  # 上一行的城市数据
    curr = row[city_cols].astype(float)      # 当前行的指数
    new_row = [row['时间']] + list(prev.values * curr.values / 100)
    result.loc[len(result)] = new_row

# 重置索引
result = result.reset_index(drop=True)
result.to_csv("processed.csv",index=False, encoding='utf-8-sig')

In [ ]:
result[["时间","西安"]].iloc[:30]

          时间          西安
0     202212  100.000000
1   202301.0  100.200000
2   202302.0  100.200000
3   202303.0  100.600800
4   202304.0  101.204405
5   202305.0  101.609222
6   202306.0  101.914050
7   202307.0  102.423620
8   202308.0  102.833315
9   202309.0  103.244648
10  202310.0  103.864116
11  202311.0  104.071844
12  202312.0  104.592203
13  202401.0  104.801388
14  202402.0  105.115792
15  202403.0  105.536255
16  202404.0  105.641791
17  202405.0  105.536150
18  202406.0  105.747222
19  202407.0  105.958716
20  202408.0  105.958716
21  202409.0  105.322964
22  202410.0  104.691026
23  202411.0  104.481644
24  202412.0  104.168199
25  202501.0  103.751526
26  202502.0  103.232769
27  202503.0  103.026303
28  202504.0  102.717224
29  202505.0  102.306356

In [ ]:
city_cols = [col for col in df.columns if col != '时间']

# 新建结果 DataFrame，第一行全是 100
result = pd.DataFrame(columns=df.columns)
first_row = ['202412'] + [100.0] * len(city_cols)
result.loc[0] = first_row

# 依次计算后续行
for i, row in df[].iterrows():
    prev = result.iloc[-1, 1:].astype(float)  # 上一行的城市数据
    curr = row[city_cols].astype(float)      # 当前行的指数
    new_row = [row['时间']] + list(prev.values * curr.values / 100)
    result.loc[len(result)] = new_row

# 重置索引
result = result.reset_index(drop=True)
result.to_csv("processed.csv",index=False, encoding='utf-8-sig')

In [53]:
result[["时间","韶关"]].iloc[50:]

        时间          韶关
50  202202  104.740950
51  202203  105.369396
52  202204  104.315702
53  202205  104.420018
54  202206  103.897918
55  202207  104.105713
56  202208  104.313925
57  202209  103.896669
58  202210  103.584979
59  202211  102.859884
60  202212  102.242725
61  202301  102.447210
62  202302  102.652105
63  202303  103.268017
64  202304  103.681090
65  202305  104.406857
66  202306  104.093637
67  202307  103.781356
68  202308  103.262449
69  202309  102.539612
70  202310  101.411676
71  202311  100.600383
72  202312   99.996780
73  202401   99.596793
74  202402   98.999212
75  202403   98.702215
76  202404   98.208704
77  202405   97.324825
78  202406   97.324825
79  202407   96.448902
80  202408   95.484413
81  202409   95.197960
82  202410   94.912366
83  202411   94.437804
84  202412   93.871177
85  202501   93.589564
86  202502   93.028026
87  202503   93.028026
88  202504   92.748942
89  202505   92.656193
90  202506   92.470881